pipeline {

    agent any

    environment {
        IMAGE_NAME = "myapp"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/AVISRJ062002/jenkins-pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {

                bat 'docker build -t %IMAGE_NAME% ./services/service1'

            }
        }

        stage('Run Container') {
            steps {

                bat '''
                docker rm -f myapp
                docker run -d --name myapp -p 8081:8080 myapp
                '''
            }
        }
    }
}