pipeline {

    agent any

    environment {
        IMAGE_NAME = "myapp"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/AVISRJ062002/jenkins-pipeline.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t %IMAGE_NAME% .'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonarqube') {

                    bat '''
                    sonar-scanner ^
                    -Dsonar.projectKey=myapp ^
                    -Dsonar.sources=. ^
                    -Dsonar.host.url=http://localhost:9000 ^
                    -Dsonar.login=YOUR_TOKEN
                    '''
                }
            }
        }

        stage('Run Container') {
            steps {

                bat '''
                docker rm -f myapp
                docker run -d --name myapp -p 8000:8000 myapp
                '''
            }
        }
    }
}